name: hrm_mobile
description: HRM mobile app with role-based navigation (User/Admin)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  file_picker: ^10.3.3
  socket_io_client: ^2.0.3+1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
